--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2026.04.13. 10:32:42
-- Server version: 5.7.44
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS barbershop;

CREATE DATABASE IF NOT EXISTS barbershop
	CHARACTER SET latin1
	COLLATE latin1_swedish_ci;

--
-- Set default database
--
USE barbershop;

--
-- Create table `users`
--
CREATE TABLE IF NOT EXISTS users (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(191) NOT NULL,
  email VARCHAR(191) NOT NULL,
  role INT(11) NOT NULL DEFAULT 3,
  phoneNumber VARCHAR(20) DEFAULT NULL,
  email_verified_at TIMESTAMP NULL DEFAULT NULL,
  password VARCHAR(191) NOT NULL,
  remember_token VARCHAR(100) DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 17,
AVG_ROW_LENGTH = 1024,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `users_email_phonenumber_unique` on table `users`
--
ALTER TABLE users 
  ADD UNIQUE INDEX users_email_phonenumber_unique(email, phoneNumber);

--
-- Create table `barbers`
--
CREATE TABLE IF NOT EXISTS barbers (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  userId BIGINT(20) UNSIGNED NOT NULL,
  profilePicture VARCHAR(125) NOT NULL,
  introduction TEXT NOT NULL,
  isActive TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 9,
AVG_ROW_LENGTH = 2048,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `barbers_userid_profilepicture_unique` on table `barbers`
--
ALTER TABLE barbers 
  ADD UNIQUE INDEX barbers_userid_profilepicture_unique(userId, profilePicture);

--
-- Create foreign key
--
ALTER TABLE barbers 
  ADD CONSTRAINT barbers_userid_foreign FOREIGN KEY (userId)
    REFERENCES users(id) ON DELETE CASCADE;

--
-- Create table `reference_pictures`
--
CREATE TABLE IF NOT EXISTS reference_pictures (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  picture VARCHAR(125) NOT NULL,
  barberId BIGINT(20) UNSIGNED NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 68,
AVG_ROW_LENGTH = 244,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `reference_pictures_picture_unique` on table `reference_pictures`
--
ALTER TABLE reference_pictures 
  ADD UNIQUE INDEX reference_pictures_picture_unique(picture);

--
-- Create foreign key
--
ALTER TABLE reference_pictures 
  ADD CONSTRAINT reference_pictures_barberid_foreign FOREIGN KEY (barberId)
    REFERENCES barbers(id) ON DELETE CASCADE;

--
-- Create table `barber_off_days`
--
CREATE TABLE IF NOT EXISTS barber_off_days (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  barberId BIGINT(20) UNSIGNED NOT NULL,
  offDay DATE NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 49,
AVG_ROW_LENGTH = 341,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `barber_off_days_barberid_offday_unique` on table `barber_off_days`
--
ALTER TABLE barber_off_days 
  ADD UNIQUE INDEX barber_off_days_barberid_offday_unique(barberId, offDay);

--
-- Create foreign key
--
ALTER TABLE barber_off_days 
  ADD CONSTRAINT barber_off_days_barberid_foreign FOREIGN KEY (barberId)
    REFERENCES barbers(id) ON DELETE CASCADE;

--
-- Create table `appointments`
--
CREATE TABLE IF NOT EXISTS appointments (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  barberId BIGINT(20) UNSIGNED NOT NULL,
  userId BIGINT(20) UNSIGNED NOT NULL,
  appointmentDate DATE NOT NULL,
  appointmentTime TIME NOT NULL,
  totalPrice INT(10) UNSIGNED NOT NULL DEFAULT 0,
  status ENUM('booked','cancelled','completed') NOT NULL DEFAULT 'booked',
  cancelledBy ENUM('none','barber','customer') NOT NULL DEFAULT 'none',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 301,
AVG_ROW_LENGTH = 163,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `idx_barber_date` on table `appointments`
--
ALTER TABLE appointments 
  ADD INDEX idx_barber_date(barberId, appointmentDate);

--
-- Create index `idx_user_date` on table `appointments`
--
ALTER TABLE appointments 
  ADD INDEX idx_user_date(userId, appointmentDate);

--
-- Create index `uniq_barber_slot` on table `appointments`
--
ALTER TABLE appointments 
  ADD UNIQUE INDEX uniq_barber_slot(barberId, appointmentDate, appointmentTime);

--
-- Create foreign key
--
ALTER TABLE appointments 
  ADD CONSTRAINT appointments_barberid_foreign FOREIGN KEY (barberId)
    REFERENCES barbers(id) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE appointments 
  ADD CONSTRAINT appointments_userid_foreign FOREIGN KEY (userId)
    REFERENCES users(id) ON DELETE CASCADE;

--
-- Create table `reviews`
--
CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  appointmentId BIGINT(20) UNSIGNED NOT NULL,
  barberId BIGINT(20) UNSIGNED NOT NULL,
  userId BIGINT(20) UNSIGNED NOT NULL,
  rating INT(11) NOT NULL,
  comment TEXT NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 74,
AVG_ROW_LENGTH = 224,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `reviews_appointmentid_barberid_userid_unique` on table `reviews`
--
ALTER TABLE reviews 
  ADD UNIQUE INDEX reviews_appointmentid_barberid_userid_unique(appointmentId, barberId, userId);

--
-- Create foreign key
--
ALTER TABLE reviews 
  ADD CONSTRAINT reviews_appointmentid_foreign FOREIGN KEY (appointmentId)
    REFERENCES appointments(id) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE reviews 
  ADD CONSTRAINT reviews_barberid_foreign FOREIGN KEY (barberId)
    REFERENCES barbers(id) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE reviews 
  ADD CONSTRAINT reviews_userid_foreign FOREIGN KEY (userId)
    REFERENCES users(id) ON DELETE CASCADE;

--
-- Create table `services`
--
CREATE TABLE IF NOT EXISTS services (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  service VARCHAR(50) NOT NULL,
  price INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 11,
AVG_ROW_LENGTH = 1638,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `services_service_unique` on table `services`
--
ALTER TABLE services 
  ADD UNIQUE INDEX services_service_unique(service);

--
-- Create table `appointment_services`
--
CREATE TABLE IF NOT EXISTS appointment_services (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  appointmentId BIGINT(20) UNSIGNED NOT NULL,
  serviceId BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 613,
AVG_ROW_LENGTH = 107,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `appointment_services_appointmentid_serviceid_unique` on table `appointment_services`
--
ALTER TABLE appointment_services 
  ADD UNIQUE INDEX appointment_services_appointmentid_serviceid_unique(appointmentId, serviceId);

--
-- Create foreign key
--
ALTER TABLE appointment_services 
  ADD CONSTRAINT appointment_services_appointmentid_foreign FOREIGN KEY (appointmentId)
    REFERENCES appointments(id) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE appointment_services 
  ADD CONSTRAINT appointment_services_serviceid_foreign FOREIGN KEY (serviceId)
    REFERENCES services(id) ON DELETE CASCADE;

--
-- Create table `sessions`
--
CREATE TABLE IF NOT EXISTS sessions (
  id VARCHAR(191) NOT NULL,
  user_id BIGINT(20) UNSIGNED DEFAULT NULL,
  ip_address VARCHAR(45) DEFAULT NULL,
  user_agent TEXT DEFAULT NULL,
  payload LONGTEXT NOT NULL,
  last_activity INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `sessions_last_activity_index` on table `sessions`
--
ALTER TABLE sessions 
  ADD INDEX sessions_last_activity_index(last_activity);

--
-- Create index `sessions_user_id_index` on table `sessions`
--
ALTER TABLE sessions 
  ADD INDEX sessions_user_id_index(user_id);

--
-- Create table `personal_access_tokens`
--
CREATE TABLE IF NOT EXISTS personal_access_tokens (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  tokenable_type VARCHAR(191) NOT NULL,
  tokenable_id BIGINT(20) UNSIGNED NOT NULL,
  name TEXT NOT NULL,
  token VARCHAR(64) NOT NULL,
  abilities TEXT DEFAULT NULL,
  last_used_at TIMESTAMP NULL DEFAULT NULL,
  expires_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `personal_access_tokens_expires_at_index` on table `personal_access_tokens`
--
ALTER TABLE personal_access_tokens 
  ADD INDEX personal_access_tokens_expires_at_index(expires_at);

--
-- Create index `personal_access_tokens_token_unique` on table `personal_access_tokens`
--
ALTER TABLE personal_access_tokens 
  ADD UNIQUE INDEX personal_access_tokens_token_unique(token);

--
-- Create index `personal_access_tokens_tokenable_type_tokenable_id_index` on table `personal_access_tokens`
--
ALTER TABLE personal_access_tokens 
  ADD INDEX personal_access_tokens_tokenable_type_tokenable_id_index(tokenable_type, tokenable_id);

--
-- Create table `password_reset_tokens`
--
CREATE TABLE IF NOT EXISTS password_reset_tokens (
  email VARCHAR(191) NOT NULL,
  token VARCHAR(191) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (email)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `migrations`
--
CREATE TABLE IF NOT EXISTS migrations (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  migration VARCHAR(191) NOT NULL,
  batch INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 13,
AVG_ROW_LENGTH = 1365,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `job_batches`
--
CREATE TABLE IF NOT EXISTS job_batches (
  id VARCHAR(191) NOT NULL,
  name VARCHAR(191) NOT NULL,
  total_jobs INT(11) NOT NULL,
  pending_jobs INT(11) NOT NULL,
  failed_jobs INT(11) NOT NULL,
  failed_job_ids LONGTEXT NOT NULL,
  options MEDIUMTEXT DEFAULT NULL,
  cancelled_at INT(11) DEFAULT NULL,
  created_at INT(11) NOT NULL,
  finished_at INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `jobs`
--
CREATE TABLE IF NOT EXISTS jobs (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  queue VARCHAR(191) NOT NULL,
  payload LONGTEXT NOT NULL,
  attempts TINYINT(3) UNSIGNED NOT NULL,
  reserved_at INT(10) UNSIGNED DEFAULT NULL,
  available_at INT(10) UNSIGNED NOT NULL,
  created_at INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `jobs_queue_index` on table `jobs`
--
ALTER TABLE jobs 
  ADD INDEX jobs_queue_index(queue);

--
-- Create table `failed_jobs`
--
CREATE TABLE IF NOT EXISTS failed_jobs (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  uuid VARCHAR(191) NOT NULL,
  `connection` TEXT NOT NULL,
  queue TEXT NOT NULL,
  payload LONGTEXT NOT NULL,
  exception LONGTEXT NOT NULL,
  failed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `failed_jobs_uuid_unique` on table `failed_jobs`
--
ALTER TABLE failed_jobs 
  ADD UNIQUE INDEX failed_jobs_uuid_unique(uuid);

--
-- Create table `cache_locks`
--
CREATE TABLE IF NOT EXISTS cache_locks (
  `key` VARCHAR(191) NOT NULL,
  owner VARCHAR(191) NOT NULL,
  expiration INT(11) NOT NULL,
  PRIMARY KEY (`key`)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `cache`
--
CREATE TABLE IF NOT EXISTS cache (
  `key` VARCHAR(191) NOT NULL,
  value MEDIUMTEXT NOT NULL,
  expiration INT(11) NOT NULL,
  PRIMARY KEY (`key`)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;